package types

type Confidence string

const (
	CONFIDENCE_UNKNOWN           Confidence = "UNKNOWN"
	CONFIDENCE_MATCH_BY_PORT     Confidence = "MATCH_BY_PORT"
	CONFIDENCE_MATCH_BY_IP       Confidence = "MATCH_BY_IP"
	CONFIDENCE_DPI_PARTIAL       Confidence = "DPI_PARTIAL"
	CONFIDENCE_DPI_PARTIAL_CACHE Confidence = "DPI_PARTIAL_CACHE"
	CONFIDENCE_DPI_CACHE         Confidence = "DPI_CACHE"
	CONFIDENCE_DPI               Confidence = "DPI"
)

const (
	NDPI_CONFIDENCE_UNKNOWN           uint16 = 0
	NDPI_CONFIDENCE_MATCH_BY_PORT     uint16 = 1
	NDPI_CONFIDENCE_MATCH_BY_IP       uint16 = 2
	NDPI_CONFIDENCE_DPI_PARTIAL       uint16 = 3
	NDPI_CONFIDENCE_DPI_PARTIAL_CACHE uint16 = 4
	NDPI_CONFIDENCE_DPI_CACHE         uint16 = 5
	NDPI_CONFIDENCE_DPI               uint16 = 6
)

var NdpiConfidenceIdMap = map[uint16]Confidence{
	NDPI_CONFIDENCE_UNKNOWN:           CONFIDENCE_UNKNOWN,
	NDPI_CONFIDENCE_MATCH_BY_PORT:     CONFIDENCE_MATCH_BY_PORT,
	NDPI_CONFIDENCE_MATCH_BY_IP:       CONFIDENCE_MATCH_BY_IP,
	NDPI_CONFIDENCE_DPI_PARTIAL:       CONFIDENCE_DPI_PARTIAL,
	NDPI_CONFIDENCE_DPI_PARTIAL_CACHE: CONFIDENCE_DPI_PARTIAL_CACHE,
	NDPI_CONFIDENCE_DPI_CACHE:         CONFIDENCE_DPI_CACHE,
	NDPI_CONFIDENCE_DPI:               CONFIDENCE_DPI,
}
