package types

type NdpiCategory uint16

func (c *NdpiCategory) ToName() string {
	name, ok := NdpiCategoryNameMap[*c]
	if !ok {
		name = ""
	}

	return name
}

const (
	NDPI_PROTOCOL_CATEGORY_UNSPECIFIED        NdpiCategory = 0
	NDPI_PROTOCOL_CATEGORY_MEDIA              NdpiCategory = 1
	NDPI_PROTOCOL_CATEGORY_VPN                NdpiCategory = 2
	NDPI_PROTOCOL_CATEGORY_MAIL               NdpiCategory = 3
	NDPI_PROTOCOL_CATEGORY_DATA_TRANSFER      NdpiCategory = 4
	NDPI_PROTOCOL_CATEGORY_WEB                NdpiCategory = 5
	NDPI_PROTOCOL_CATEGORY_SOCIAL_NETWOR      NdpiCategory = 6
	NDPI_PROTOCOL_CATEGORY_DOWNLOAD_FT        NdpiCategory = 7
	NDPI_PROTOCOL_CATEGORY_GAME               NdpiCategory = 8
	NDPI_PROTOCOL_CATEGORY_CHAT               NdpiCategory = 9
	NDPI_PROTOCOL_CATEGORY_VOIP               NdpiCategory = 10
	NDPI_PROTOCOL_CATEGORY_DATABASE           NdpiCategory = 11
	NDPI_PROTOCOL_CATEGORY_REMOTE_ACCESS      NdpiCategory = 12
	NDPI_PROTOCOL_CATEGORY_CLOUD              NdpiCategory = 13
	NDPI_PROTOCOL_CATEGORY_NETWORK            NdpiCategory = 14
	NDPI_PROTOCOL_CATEGORY_COLLABORATIVE      NdpiCategory = 15
	NDPI_PROTOCOL_CATEGORY_RPC                NdpiCategory = 16
	NDPI_PROTOCOL_CATEGORY_STREAMING          NdpiCategory = 17
	NDPI_PROTOCOL_CATEGORY_SYSTEM_OS          NdpiCategory = 18
	NDPI_PROTOCOL_CATEGORY_SW_UPDATE          NdpiCategory = 19
	NDPI_PROTOCOL_CATEGORY_CUSTOM_1           NdpiCategory = 20
	NDPI_PROTOCOL_CATEGORY_CUSTOM_2           NdpiCategory = 21
	NDPI_PROTOCOL_CATEGORY_CUSTOM_3           NdpiCategory = 22
	NDPI_PROTOCOL_CATEGORY_CUSTOM_4           NdpiCategory = 23
	NDPI_PROTOCOL_CATEGORY_CUSTOM_5           NdpiCategory = 24
	NDPI_PROTOCOL_CATEGORY_MUSIC              NdpiCategory = 25
	NDPI_PROTOCOL_CATEGORY_VIDEO              NdpiCategory = 26
	NDPI_PROTOCOL_CATEGORY_SHOPPING           NdpiCategory = 27
	NDPI_PROTOCOL_CATEGORY_PRODUCTIVITY       NdpiCategory = 28
	NDPI_PROTOCOL_CATEGORY_FILE_SHARING       NdpiCategory = 29
	NDPI_PROTOCOL_CATEGORY_CONNECTIVITY_CHECK NdpiCategory = 30
	NDPI_PROTOCOL_CATEGORY_IOT_SCADA          NdpiCategory = 31
	NDPI_PROTOCOL_CATEGORY_VIRTUAL_ASSISTANT  NdpiCategory = 32
	NDPI_PROTOCOL_CATEGORY_CYBERSECURITY      NdpiCategory = 33
	CUSTOM_CATEGORY_MINING                    NdpiCategory = 99
	CUSTOM_CATEGORY_MALWARE                   NdpiCategory = 100
	CUSTOM_CATEGORY_ADVERTISEMENT             NdpiCategory = 101
	CUSTOM_CATEGORY_BANNED_SITE               NdpiCategory = 102
	CUSTOM_CATEGORY_SITE_UNAVAILABLE          NdpiCategory = 103
	CUSTOM_CATEGORY_ALLOWED_SITE              NdpiCategory = 104
	CUSTOM_CATEGORY_ANTIMALWARE               NdpiCategory = 105
)

const (
	CATEGORY_UNSPECIFIED        string = "UNSPECIFIED"
	CATEGORY_MEDIA              string = "MEDIA"
	CATEGORY_VPN                string = "VPN"
	CATEGORY_MAIL               string = "MAIL"
	CATEGORY_DATA_TRANSFER      string = "DATA_TRANSFER"
	CATEGORY_WEB                string = "WEB"
	CATEGORY_SOCIAL_NETWOR      string = "SOCIAL_NETWOR"
	CATEGORY_DOWNLOAD_FT        string = "DOWNLOAD_FT"
	CATEGORY_GAME               string = "GAME"
	CATEGORY_CHAT               string = "CHAT"
	CATEGORY_VOIP               string = "VOIP"
	CATEGORY_DATABASE           string = "DATABASE"
	CATEGORY_REMOTE_ACCESS      string = "REMOTE_ACCESS"
	CATEGORY_CLOUD              string = "CLOUD"
	CATEGORY_NETWORK            string = "NETWORK"
	CATEGORY_COLLABORATIVE      string = "COLLABORATIVE"
	CATEGORY_RPC                string = "RPC"
	CATEGORY_STREAMING          string = "STREAMING"
	CATEGORY_SYSTEM_OS          string = "SYSTEM_OS"
	CATEGORY_SW_UPDATE          string = "SW_UPDATE"
	CATEGORY_CUSTOM_1           string = "CUSTOM_1"
	CATEGORY_CUSTOM_2           string = "CUSTOM_2"
	CATEGORY_CUSTOM_3           string = "CUSTOM_3"
	CATEGORY_CUSTOM_4           string = "CUSTOM_4"
	CATEGORY_CUSTOM_5           string = "CUSTOM_5"
	CATEGORY_MUSIC              string = "MUSIC"
	CATEGORY_VIDEO              string = "VIDEO"
	CATEGORY_SHOPPING           string = "SHOPPING"
	CATEGORY_PRODUCTIVITY       string = "PRODUCTIVITY"
	CATEGORY_FILE_SHARING       string = "FILE_SHARING"
	CATEGORY_CONNECTIVITY_CHECK string = "CONNECTIVITY_CHECK"
	CATEGORY_IOT_SCADA          string = "IOT_SCADA"
	CATEGORY_VIRTUAL_ASSISTANT  string = "VIRTUAL_ASSISTANT"
	CATEGORY_CYBERSECURITY      string = "CYBERSECURITY"
	CATEGORY_MINING             string = "MINING"
	CATEGORY_MALWARE            string = "MALWARE"
	CATEGORY_ADVERTISEMENT      string = "ADVERTISEMENT"
	CATEGORY_BANNED_SITE        string = "BANNED_SITE"
	CATEGORY_SITE_UNAVAILABLE   string = "SITE_UNAVAILABLE"
	CATEGORY_ALLOWED_SITE       string = "ALLOWED_SITE"
	CATEGORY_ANTIMALWARE        string = "ANTIMALWARE"
)

var NdpiCategoryNameMap = map[NdpiCategory]string{
	NDPI_PROTOCOL_CATEGORY_UNSPECIFIED:        CATEGORY_UNSPECIFIED,
	NDPI_PROTOCOL_CATEGORY_MEDIA:              CATEGORY_MEDIA,
	NDPI_PROTOCOL_CATEGORY_VPN:                CATEGORY_VPN,
	NDPI_PROTOCOL_CATEGORY_MAIL:               CATEGORY_MAIL,
	NDPI_PROTOCOL_CATEGORY_DATA_TRANSFER:      CATEGORY_DATA_TRANSFER,
	NDPI_PROTOCOL_CATEGORY_WEB:                CATEGORY_WEB,
	NDPI_PROTOCOL_CATEGORY_SOCIAL_NETWOR:      CATEGORY_SOCIAL_NETWOR,
	NDPI_PROTOCOL_CATEGORY_DOWNLOAD_FT:        CATEGORY_DOWNLOAD_FT,
	NDPI_PROTOCOL_CATEGORY_GAME:               CATEGORY_GAME,
	NDPI_PROTOCOL_CATEGORY_CHAT:               CATEGORY_CHAT,
	NDPI_PROTOCOL_CATEGORY_VOIP:               CATEGORY_VOIP,
	NDPI_PROTOCOL_CATEGORY_DATABASE:           CATEGORY_DATABASE,
	NDPI_PROTOCOL_CATEGORY_REMOTE_ACCESS:      CATEGORY_REMOTE_ACCESS,
	NDPI_PROTOCOL_CATEGORY_CLOUD:              CATEGORY_CLOUD,
	NDPI_PROTOCOL_CATEGORY_NETWORK:            CATEGORY_NETWORK,
	NDPI_PROTOCOL_CATEGORY_COLLABORATIVE:      CATEGORY_COLLABORATIVE,
	NDPI_PROTOCOL_CATEGORY_RPC:                CATEGORY_RPC,
	NDPI_PROTOCOL_CATEGORY_STREAMING:          CATEGORY_STREAMING,
	NDPI_PROTOCOL_CATEGORY_SYSTEM_OS:          CATEGORY_SYSTEM_OS,
	NDPI_PROTOCOL_CATEGORY_SW_UPDATE:          CATEGORY_SW_UPDATE,
	NDPI_PROTOCOL_CATEGORY_CUSTOM_1:           CATEGORY_CUSTOM_1,
	NDPI_PROTOCOL_CATEGORY_CUSTOM_2:           CATEGORY_CUSTOM_2,
	NDPI_PROTOCOL_CATEGORY_CUSTOM_3:           CATEGORY_CUSTOM_3,
	NDPI_PROTOCOL_CATEGORY_CUSTOM_4:           CATEGORY_CUSTOM_4,
	NDPI_PROTOCOL_CATEGORY_CUSTOM_5:           CATEGORY_CUSTOM_5,
	NDPI_PROTOCOL_CATEGORY_MUSIC:              CATEGORY_MUSIC,
	NDPI_PROTOCOL_CATEGORY_VIDEO:              CATEGORY_VIDEO,
	NDPI_PROTOCOL_CATEGORY_SHOPPING:           CATEGORY_SHOPPING,
	NDPI_PROTOCOL_CATEGORY_PRODUCTIVITY:       CATEGORY_PRODUCTIVITY,
	NDPI_PROTOCOL_CATEGORY_FILE_SHARING:       CATEGORY_FILE_SHARING,
	NDPI_PROTOCOL_CATEGORY_CONNECTIVITY_CHECK: CATEGORY_CONNECTIVITY_CHECK,
	NDPI_PROTOCOL_CATEGORY_IOT_SCADA:          CATEGORY_IOT_SCADA,
	NDPI_PROTOCOL_CATEGORY_VIRTUAL_ASSISTANT:  CATEGORY_VIRTUAL_ASSISTANT,
	NDPI_PROTOCOL_CATEGORY_CYBERSECURITY:      CATEGORY_CYBERSECURITY,
	CUSTOM_CATEGORY_MINING:                    CATEGORY_MINING,
	CUSTOM_CATEGORY_MALWARE:                   CATEGORY_MALWARE,
	CUSTOM_CATEGORY_ADVERTISEMENT:             CATEGORY_ADVERTISEMENT,
	CUSTOM_CATEGORY_BANNED_SITE:               CATEGORY_BANNED_SITE,
	CUSTOM_CATEGORY_SITE_UNAVAILABLE:          CATEGORY_SITE_UNAVAILABLE,
	CUSTOM_CATEGORY_ALLOWED_SITE:              CATEGORY_ALLOWED_SITE,
	CUSTOM_CATEGORY_ANTIMALWARE:               CATEGORY_ANTIMALWARE,
}
